# Generated by Django 5.2.4 on 2025-07-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_barbearia_horariodisponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariodisponivel',
            name='duracao',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
